/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testsmaker;

import BDConnection.ExcelConnection;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.EnumSet;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class RandomManual extends javax.swing.JFrame {

    private String age;
    private String[] tests;
    private ArrayList<String> tittles;
    private int idUser;
    private boolean r;
    ArrayList<String> allTitles;

    /**
     * @param tests
     * @param age
     */
    public RandomManual(String[] tests, int age, int idUser) {
        initComponents();
        this.idUser = idUser;
        setLocationRelativeTo(null);
        setResizable(false);
        changeOnClose();
        this.age = range(age);
        this.tests = tests;
        tittles = ExcelConnection.getStoriesTittlesinRange(this.age);
        try {
            allTitles = ExcelConnection.getStoriesTittles();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error contactate con el desarrollador" + "\n" + " Mensaje de error: " + e.getMessage());
        }

    }

    
    private void changeOnClose(){
        try{
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
             addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e){
                dispose();
                new Main().setVisible(true);
            }
           });
        }catch(Exception e){
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            System.err.print(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Aleatoria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Manual");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Que tipo de prueba desea?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String range(int age) {
        String r;
        if (age == 0) {
            r = null;
        } else if (age < 14) {
            r = "ninios";
        } else if (age < 18) {
            r = "Jovenes";
        } else {
            r = "Adultos";
        }
        return r;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rando = 0;
        do {

            rando = new Random().nextInt(tittles.size());
        } while (checkTitleUsed(rando, true));
        int id = 0;
        for(int i = 0 ; i < allTitles.size() ; i++){
            if(tittles.get(rando).equals(allTitles.get(i))){
                id = i;
                break;
            }
        }
        launchTest(id);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = -1;
        boolean used = false;
        String u = "";
        do {
            if (used) {
                u = " - El anterior id ya fue usado con este usuario";
            }
            String sId = JOptionPane.showInputDialog("Inserte el ID de la prueba" + u);
            try {
                id = Integer.parseInt(sId);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor solo numeros en el campo de IqD");
            }
        } while (used = checkTitleUsed(id - 1, false));
        launchTest(id-1);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void launchTest(int id) {
        String[] answerWords = {};
        answerWords = ExcelConnection.getAnwerWords(allTitles.get(id));
        String[] answers = answerWords[1].split(",");
        int words = Integer.parseInt(answerWords[0]);
        new TestLauncher(answers, words, allTitles.get(id), idUser, id + 1).setVisible(true);
        dispose();

    }

    private boolean checkTitleUsed(int id, boolean r) {
        boolean used = false;
        this.r = r;
        String test = "";
        if (id >= 0) {
            if (r) {
                test = tittles.get(id);
            } else {
                test = allTitles.get(id);
            }
            for (String s : tests) {
                if (test.equals(s)) {
                    used = true;
                    break;
                }
            }
        }
        return used;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandomManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandomManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandomManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandomManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RandomManual(new String[]{" "}, 19, 1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
