/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testsmaker;

import BDConnection.ExcelConnection;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class TestLauncher extends javax.swing.JFrame {

    private Reloj reloj;
    public boolean estado;
    private int time;
    private ArrayList<JComboBox<String>> questions;
    private String[] answer;
    private int comp;
    private int words;
    private int ppm , id, idStorie;
    

    /**
     * Creates new form TestLauncher
     *
     * @param answer
     * @param words
     * @param tittle
     * @param id
     * @param idStorie
     */
    public TestLauncher(String[] answer, int words, String tittle, int id, int idStorie) {
        initComponents();
        this.answer = answer;
        this.id = id;
        this.idStorie = idStorie;
        setLocationRelativeTo(null);
        setResizable(false);
        changeOnClose();
        reloj = new Reloj(jLabel6);
        this.words = words;
        ppm = 0;
        jLabel2.setText(tittle);
        questions = new ArrayList<>();
        comp = 0;
        ArrayList<JLabel> titleQ = new ArrayList<>();
        int x = answer.length;
        for (int i = 0; i < answer.length; i++) {
            questions.add(new JComboBox<String>());
            titleQ.add(new JLabel());
        }

        for (int i = 0; i < x; i++) {
            questions.get(i).setBounds(50, 50 + i * 70, 250, 30);
            titleQ.get(i).setBounds(50, 25 + i * 70, 250, 20);
            titleQ.get(i).setVisible(true);
            titleQ.get(i).setText("Pregunta Nro: " + (i + 1));
            questions.get(i).setVisible(true);
            questions.get(i).addItem(" ");
            questions.get(i).addItem("A");
            questions.get(i).addItem("B");
            questions.get(i).addItem("C");
            questions.get(i).addItem("D");
            questions.get(i).addItem("E");
            add(questions.get(i));
            add(titleQ.get(i));

        }
    }

    
    
    private void changeOnClose(){
        try{
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
             addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e){
                dispose();
                new Main().setVisible(true);
            }
           });
        }catch(Exception e){
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            System.err.print(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo de la Obra");
        jLabel1.setToolTipText("");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Cronometro");

        jButton1.setText("Empezar Cronometro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Calificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Comprension:");

        jLabel5.setText("PPM: ");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 90)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("00 : 00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(224, 224, 224)))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String state = jButton1.getText();
        jButton1.setText("Detener Cronometro");
        if (state.equals("Empezar Cronometro")) {

            estado = true;

            reloj = new Reloj(jLabel6);
            Thread hilo = new Thread() {
                int mili = 0;

                public void run() {
                    for (;;) {
                        if (estado) {
                            try {
                                mili++;
                                sleep(1);
                                if (mili == 540) {
                                    reloj.grow();
                                    mili = 0;
                                }
                            } catch (InterruptedException ex) {

                            }
                        } else {
                            break;
                        }
                    }
                }
            };
            hilo.start();

        } else {
            jButton1.setText("Empezar Cronometro");
            estado = false;
            String stime = jLabel6.getText();
            time = Integer.parseInt(stime.substring(0, 2)) * 60 + Integer.parseInt(stime.substring(5, 7));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        time = 0;
        reloj.restart();
        questions.forEach(jc -> {
            jc.setSelectedIndex(0);
        });
        jLabel4.setText("Comprension: ");
        jLabel5.setText("PPM:         ");
        ppm = 0;
        comp = 0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String state = jButton3.getText();
        if (state.equals("Calificar")) {
            if (check()) {
                jButton3.setText("Subir Resultados");
            }
        }else{
            try {
                ExcelConnection.updateTest(id, idStorie, ppm, comp);
                JOptionPane.showMessageDialog(null,"Prueba subida con exito!");
                new Main().setVisible(true);
                dispose();
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Error contactate con el desarrollador"+"\n"+" Mensaje de error: "+e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private boolean check() {
        boolean empty = false;
        for (JComboBox jc : questions) {
            if (jc.getSelectedItem().equals(" ")) {
                jc.setBackground(Color.RED);
                empty = true;

            }
        }
        if (empty) {
            JOptionPane.showMessageDialog(null, "Rellena todos los espacios");
            questions.forEach(jc -> {
                jc.setBackground(Color.WHITE);
            });
        } else if (time == 0) {
            JOptionPane.showMessageDialog(null, "Tiempo 0 es invalido");

        } else {
            comp = checkAnswers();
            jLabel4.setText("Comprension: " + comp);
            ppm = 60 * words / time;
            jLabel5.setText("PPM:         " + ppm);
        }
        return !empty && time != 0;
    }

    private int checkAnswers() {
        float size = (float) questions.size();
        float x = 100 / size;
        float c = 0;
        for (int i = 0; i < questions.size(); i++) {
            if (questions.get(i).getSelectedItem().toString().equals(answer[i].toUpperCase())) {
                c += x;
            }
        }
        return (int) c;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestLauncher(new String[]{"b", "c", "b"}, 250, "Las matematicas",4,2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
